Newdesign
Infratab/Website-IN pull request #5
Opened 2017-06-01 05:08 UTC by priyanka0901

2017-06-02 04:16 UTC, priyanka1110 requested changes

2017-06-02 04:16 UTC, priyanka1110 commented on careers.html
> +  <title>Infratab Bangalore Pvt. Ltd</title>
@priyanka0901 Favicon icon should be added first if you are starting any project.

2017-06-02 04:16 UTC, priyanka1110 commented on careers.html
> +            <div class="hiring-box">
@priyanka0901 Use materializescss card instead of writing your own structure and CSS

2017-06-02 04:16 UTC, priyanka1110 commented on careers.html
> +                <p class="hiring-button">Apply</p>
@priyanka0901  It should be the `button` or `a` tag as it's clear that it is a button.

2017-06-02 04:16 UTC, priyanka1110 commented on careers.html
> +      <div class="col l2 m2 s2">
@priyanka0901 Grid should always go from small screen to big screen not from big to small. 
`For Ex: <div class="col s2 m2 l2"></div>`
If the grid value is same for all the screen then we don't have mention all the screen it should only `col s2`.

2017-06-02 04:23 UTC, priyanka1110 commented on careers.html
> +    <p class="horizontal-line"></p>
@priyanka0901 Why `p` tag for adding a horizontal line. There is two other way to do it adding `<hr>` tag or else border-bottom from the content container or else border-top from copyright section.

2017-06-02 04:27 UTC, priyanka1110 requested changes

2017-06-02 04:27 UTC, priyanka1110 commented on careers.html
> +<script src="https://use.fontawesome.com/0d9d5c45b7.js"></script>
@priyanka0901 Don't load CDN links use it locally.

2017-06-02 04:30 UTC, priyanka1110 commented on careers.html
> +      <a class="team-button" id="js-join-scroll">Join us</a>
@priyanka0901 We should use only `camelcase` for `ID` naming convention. @Swathi8 Can correct me if I am wrong.

2017-06-02 04:38 UTC, priyanka1110 commented on sass/pages/_careers.scss
> +.team-button {
@priyanka0901 Why are you writing your own CSS for the button if it already available in the library.

2017-06-02 04:44 UTC, priyanka1110 commented on careers.html
> +      <a class="team-button" id="js-join-scroll">Join us</a>
@priyanka0901 From the design you know that this raised button then it should be written in `button` tag, not `a` tag. `a` tag should be used only for linking and if you want to make the flat button.

2017-06-02 05:01 UTC, priyanka0901 commented on careers.html
> +  <title>Infratab Bangalore Pvt. Ltd</title>
I asked you told its fine to add font awsome

2017-06-02 05:03 UTC, priyanka1110 commented on careers.html
> +  <title>Infratab Bangalore Pvt. Ltd</title>
@priyanka0901 I am telling about favicon icon. https://en.wikipedia.org/wiki/Favicon

2017-06-02 07:32 UTC, priyanka0901 commented on careers.html
> +  <title>Infratab Bangalore Pvt. Ltd</title>
done

2017-06-02 07:32 UTC, priyanka0901 commented on careers.html
> +            <div class="hiring-box">
done

2017-06-02 07:33 UTC, priyanka0901 commented on careers.html
> +                <p class="hiring-button">Apply</p>
done

2017-06-02 07:38 UTC, priyanka0901 commented on careers.html
> +    <p class="horizontal-line"></p>
done

2017-06-02 07:41 UTC, priyanka0901 commented on sass/pages/_careers.scss
> +.team-button {
done

2017-06-02 07:45 UTC, priyanka0901 commented on careers.html
> +      <a class="team-button" id="js-join-scroll">Join us</a>
done

2017-06-02 07:57 UTC, priyanka0901 commented on careers.html
> +<script src="https://use.fontawesome.com/0d9d5c45b7.js"></script>
done

2017-06-02 11:28 UTC, priyanka1110 commented on careers.html
> +              <a href="https://angel.co/infratab/jobs/45319-ui-developer" class="green-color">Apply</a>
@priyanka0901 Open `apply` button links into the new tab.

2017-06-02 11:36 UTC, priyanka1110 commented on careers.html
> +            <img src="img/teamgroup.png" class="group-image">
@priyanka0901 Add proper folder for img.

2017-06-08 06:14 UTC, priyanka1110 commented
This PR is no longer required so closing it.

2017-06-08 06:14 UTC, closed without merging